### ISSUE TITLE
Utilisation d'organizations

### ISSUE THREAD

**Issue by rgrunbla** [Blopausore/projet-informatique#1]
Hello,

Il faudrait créer une organization github, plutôt qu'un unique dépôt, et inviter l'ensemble des membres dans cette organization…

Voir https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations

Notamment, je ne vois pas qui participe au projet avec un unique dépôt comme actuellement…

**Comment by Blopausore** [comment]
J'attendais qu'il m'envoit leur pseudo. Je m'en occupe!

**Comment by Blopausore** [comment]
J'attendais qu'ils m'envoient leur pseudo. Je m'en occupe.
